### ISSUE TITLE
Crop counting using plant-detection in aerial image.

### ISSUE THREAD

**Issue by Geo-Trackers** [gabrielburnworth/plant-detection#6]
Dear All,  
I intend to apply plant-detection for counting number of banana plantation in an aerial image taken above 50-60 m above the ground. Can this be fit for my purpose? Has anyone applied this for similar purpose using Drones?

I look forward to hear from you.
Best, 
Suman
![dji_0714](https://user-images.githubusercontent.com/7304644/33524702-9228ff1c-d7d6-11e7-92a6-e929885c3e17.JPG)

**Comment by gabrielburnworth** [comment]
This software is currently designed to process images at 0.5m height of well-separated plants at their early stages, with the goal of detecting weed sprouts for removal by FarmBot.

A good guideline in computer vision is the easier you make it for a human, the easier it is for the computer. If possible, it would be very difficult for a human to accurately count the number of plants in the image you provided. Since your goal is centered around detecting a single type of mature plant, machine learning would be applicable, but, if possible, it would be very difficult.
